# Generated by Django 6.0.4 on 2026-04-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_enrollmentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksubmission',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='teacher_feedback',
            field=models.TextField(blank=True, default=''),
        ),
    ]
