# Generated by Django 5.1.15 on 2026-04-22 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_tasksubmission_retry_support'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasksubmission',
            options={'ordering': ['-submitted_at']},
        ),
    ]
