from django.urls import include, path
from rest_framework.routers import DefaultRouter

from .views import (
    CompleteLessonView,
    EnrollCourseView,
    EnrollmentViewSet,
    LessonQuizView,
    LessonTaskView,
    MyCoursesView,
    MyEnrollmentRequestsView,
    MyTaskSubmissionsView,
    ProgressRecordViewSet,
    ProgressSummaryView,
    SubmitQuizView,
    SubmitTaskView,
    TaskViewSet,
    TeacherQuizChoiceCreateView,
    TeacherQuizChoiceDetailView,
    TeacherQuizCreateView,
    TeacherQuizDetailView,
    TeacherQuizQuestionCreateView,
    TeacherQuizQuestionDetailView,
    TeacherQuizSubmissionsView,
    TeacherEnrollmentRequestsView,
    TeacherMyChoicesView,
    TeacherMyQuestionsView,
    TeacherMyQuizzesView,
    TeacherMyTasksView,
    TeacherStudentProgressView,
    TeacherTaskCreateView,
    TeacherTaskDetailView,
    TeacherReviewTaskSubmissionView,
    TeacherTaskSubmissionsView,
    TeacherUpdateEnrollmentRequestView,
)

router = DefaultRouter()
router.register("enrollments", EnrollmentViewSet, basename="enrollment")
router.register("tasks", TaskViewSet, basename="task")
router.register("progress", ProgressRecordViewSet, basename="progress")

urlpatterns = [
    path("enroll/<int:course_id>/", EnrollCourseView.as_view(), name="enroll-course"),
    path("lessons/<int:lesson_id>/complete/", CompleteLessonView.as_view(), name="complete-lesson"),
    path("lessons/<int:lesson_id>/quiz/", LessonQuizView.as_view(), name="lesson-quiz"),
    path("lessons/<int:lesson_id>/quiz/submit/", SubmitQuizView.as_view(), name="submit-quiz"),
    path("lessons/<int:lesson_id>/task/", LessonTaskView.as_view(), name="lesson-task"),
    path("lessons/<int:lesson_id>/task/submit/", SubmitTaskView.as_view(), name="submit-task"),
    path("teacher/quizzes/", TeacherQuizCreateView.as_view(), name="teacher-create-quiz"),
    path("teacher/quizzes/<int:pk>/", TeacherQuizDetailView.as_view(), name="teacher-quiz-detail"),
    path("teacher/questions/", TeacherQuizQuestionCreateView.as_view(), name="teacher-create-question"),
    path("teacher/questions/<int:pk>/", TeacherQuizQuestionDetailView.as_view(), name="teacher-question-detail"),
    path("teacher/choices/", TeacherQuizChoiceCreateView.as_view(), name="teacher-create-choice"),
    path("teacher/choices/<int:pk>/", TeacherQuizChoiceDetailView.as_view(), name="teacher-choice-detail"),
    path("teacher/tasks/", TeacherTaskCreateView.as_view(), name="teacher-create-task"),
    path("teacher/tasks/<int:pk>/", TeacherTaskDetailView.as_view(), name="teacher-task-detail"),
    path("teacher/my-quizzes/", TeacherMyQuizzesView.as_view(), name="teacher-my-quizzes"),
    path("teacher/my-questions/", TeacherMyQuestionsView.as_view(), name="teacher-my-questions"),
    path("teacher/my-choices/", TeacherMyChoicesView.as_view(), name="teacher-my-choices"),
    path("teacher/my-tasks/", TeacherMyTasksView.as_view(), name="teacher-my-tasks"),
    path("teacher/enrollment-requests/", TeacherEnrollmentRequestsView.as_view(), name="teacher-enrollment-requests"),
    path(
        "teacher/enrollment-requests/<int:request_id>/<str:action>/",
        TeacherUpdateEnrollmentRequestView.as_view(),
        name="teacher-update-enrollment-request",
    ),
    path("teacher/student-progress/", TeacherStudentProgressView.as_view(), name="teacher-student-progress"),
    path("teacher/quiz-submissions/", TeacherQuizSubmissionsView.as_view(), name="teacher-quiz-submissions"),
    path("teacher/task-submissions/", TeacherTaskSubmissionsView.as_view(), name="teacher-task-submissions"),
    path(
        "teacher/task-submissions/<int:submission_id>/review/",
        TeacherReviewTaskSubmissionView.as_view(),
        name="teacher-review-task-submission",
    ),
    path("my-courses/", MyCoursesView.as_view(), name="my-courses"),
    path("my-enrollment-requests/", MyEnrollmentRequestsView.as_view(), name="my-enrollment-requests"),
    path("my-task-submissions/", MyTaskSubmissionsView.as_view(), name="my-task-submissions"),
    path("progress-summary/", ProgressSummaryView.as_view(), name="progress-summary"),
    path("", include(router.urls)),
]
